version: '3.4'

services:
  master:
    image: mysql
    container_name: master
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul 
    ports:
      - "3306:3306"
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  slave:
    image: mysql
    container_name: slave
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    ports:
      - "3307:3306"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./slave/my.cnf:/etc/mysql/my.cnf
  test:
    container_name: test
    image: centos:7 
    command: bash
